"""Fractal quadtree episodic memory (Felix's design, R70).

Every completed turn's _sanitize-drop list (the messages compacted out of
the live context) is summarized into a ≤COMPACT_ENTRY_MAX-char entry at
level 0 of `memory/qtree/L0.md`. Whenever a level has 4 NEW unrolled
entries, those four are summarized into ONE new entry (≤4000 chars)
appended to the level above; new levels are created as needed (no level
limit). Children are NEVER deleted — a level file is the complete
fine-grained log of its era (browsable via ws.read), the level above is
the coarser digest. The agent's system prompt always carries the LATEST
entry of EVERY level — coarse ancient history and fine recent history at
the same time.

Summaries are generated by the same metered provider stack as normal
turns (proxy /v1/jobs, class "task" — auxiliary, never agent-class
billing), single-shot, no tools. All state is plain markdown files in the
workspace, so an operator (or the agent) can read and edit the whole
tree by hand.

Layout:
  memory/qtree/L0.md   entries:  "- [2026-10-08 18:20] <summary>" (append-only)
  memory/qtree/L1.md   …         newest last
  memory/qtree/meta.json          {"0": {"entries": n, "rolled": r}, ...}
"""

from __future__ import annotations

import asyncio
import json
import os
import re
import sys
from datetime import datetime, timezone

COMPACT_ENTRY_MAX = 4000      # Felix: max chars per summary entry
COMPACT_FANOUT = 4            # Felix: 4 entries on a level -> 1 above
# Felix 2026-10-08: modern models carry ~1M-token windows — compact at
# 200k-400k tokens. Trigger 1.2M chars (~300k tokens); the oldest half is
# summarized away each time (~150k tokens removed per compaction).
COMPACT_TRIGGER_CHARS = 1_200_000
COMPACT_TRIGGER_MSGS = 400    # count path; below _sanitize's 500-msg ceiling
QTREE_DIR = "memory/qtree"

_SUMMARY_PROMPT = """You maintain episodic memory for an autonomous agent. \
Summarize the material below into a dense factual digest. Rules:
- preserve: decisions, rulings, names, ids, numbers, dates, errors + fixes, \
open questions, state changes
- drop: pleasantry, restatements, tool-call scaffolding
- plain prose or tight bullet lines, no headings
- max {limit} characters — the LAST details matter most when space runs out
- write in English

Material:
{material}"""


def _now() -> datetime:
    return datetime.now(timezone.utc)


def qtree_paths(workspace: str) -> dict:
    base = os.path.join(workspace, QTREE_DIR)
    return {"base": base,
            "meta": os.path.join(base, "meta.json")}


def _level_file(base: str, level: int) -> str:
    return os.path.join(base, f"L{level}.md")


def load_meta(workspace: str) -> dict:
    p = qtree_paths(workspace)
    try:
        with open(p["meta"]) as f:
            return json.load(f)
    except (OSError, json.JSONDecodeError):
        return {}


def _save_meta(workspace: str, meta: dict) -> None:
    p = qtree_paths(workspace)
    os.makedirs(p["base"], exist_ok=True)
    with open(p["meta"], "w") as f:
        json.dump(meta, f, indent=1, sort_keys=True)


def _lvl(meta: dict, level: int) -> dict:
    """entries written at this level; rolled = already summarized upward."""
    return meta.setdefault(str(level), {"entries": 0, "rolled": 0})


def _unrolled(workspace: str, meta: dict, level: int) -> int:
    """Entries not yet summarized into the level above."""
    m = _lvl(meta, level)
    written = len(read_entries(workspace, level))
    return max(0, written - m.get("rolled", 0))


def read_entries(workspace: str, level: int) -> list[str]:
    """Entry lines of a level file, oldest first (append-only files)."""
    base = qtree_paths(workspace)["base"]
    try:
        with open(_level_file(base, level), encoding="utf-8") as f:
            return [l.rstrip("\n") for l in f if l.strip()]
    except OSError:
        return []


def _append_entry(workspace: str, level: int, line: str) -> None:
    base = qtree_paths(workspace)["base"]
    os.makedirs(base, exist_ok=True)
    with open(_level_file(base, level), "a", encoding="utf-8") as f:
        f.write(line + "\n")


def unrolled_count(workspace: str, level: int) -> int:
    """How many NEW entries at this level await rollup (4 = roll)."""
    return _unrolled(workspace, load_meta(workspace), level)


# --------------------------------------------------------------------------
# generation
# --------------------------------------------------------------------------

async def _summarize(material: str, limit: int, gen_fn) -> str:
    """gen_fn(prompt) -> str; returns material unchanged if generation is
    unavailable (never fail a turn because memory could not be written)."""
    try:
        out = await gen_fn(_SUMMARY_PROMPT.format(material=material,
                                                  limit=limit))
    except Exception as e:  # noqa: BLE001 — memory must never break the loop
        print(f"[qtree] summarize failed ({e}); keeping raw tail",
              file=sys.stderr)
        return material[:limit]
    out = (out or "").strip()
    return out if out else material[:limit]


async def record_compaction(workspace: str, dropped: list[dict],
                            gen_fn) -> dict:
    """Called after a turn when `dropped` messages left the context.
    Summarizes them into a fresh L0 entry, then rolls up while a level
    holds 4 UNROLLED entries (children are kept on disk — the quadtree
    never loses fine detail, the pointer just advances)."""
    if not dropped:
        return {"entries": 0}
    material = "\n".join(
        f"[{m.get('role')}] {m.get('content') or ''}" for m in dropped)
    stamp = _now().strftime("%Y-%m-%d %H:%M")
    summary = await _summarize(material, COMPACT_ENTRY_MAX, gen_fn)
    line = line_for(summary, stamp)
    _append_entry(workspace, 0, line)

    meta = load_meta(workspace)
    _lvl(meta, 0)["entries"] += 1
    rolled = 0
    level = 0
    while _unrolled(workspace, meta, level) >= COMPACT_FANOUT:
        entries = read_entries(workspace, level)
        m = _lvl(meta, level)
        four = entries[m["rolled"]:m["rolled"] + COMPACT_FANOUT]
        summary = await _summarize("\n".join(four), COMPACT_ENTRY_MAX, gen_fn)
        _append_entry(workspace, level + 1, line_for(summary, stamp))
        _lvl(meta, level + 1)["entries"] += 1
        m["rolled"] += COMPACT_FANOUT
        rolled += 1
        level += 1
    _save_meta(workspace, meta)
    return {"entries": 1, "rolled": rolled}


def line_for(summary: str, stamp: str) -> str:
    return f"- [{stamp}] {summary}".replace("\n", " ")[:COMPACT_ENTRY_MAX]


def context_block(workspace: str, budget: int = 6000) -> str:
    """The always-in-context view: newest entry of every level, fine→coarse.
    Fits `budget` chars by trimming the COARSEST levels first — the recent
    fine-grained entry (L0) is always the last thing to go (issue #5: the
    trim used to drop L0 first and keep ancient digests — backwards)."""
    meta = load_meta(workspace)
    if not meta:
        return ""
    lines: list[str] = []
    for level in sorted(int(k) for k in meta):
        entries = read_entries(workspace, level)
        if entries:
            # newest entry of the level, minus the leading "- [ts] "
            body = entries[-1]
            body = re.sub(r"^- \[[^\]]+\] ", "", body)
            # an L(n) entry summarizes 4^n L0 compactions (fanout 4)
            tag = ("recent" if level == 0
                   else f"~{4 ** level} compactions ago")
            lines.append(f"[{tag}] {body}")
    text = "\n".join(lines)
    if len(text) > budget:
        # lines are fine→coarse: L0 FIRST, coarsest LAST. Drop from the
        # END (coarsest, oldest era) until it fits — L0 is never dropped
        # while more than one line remains.
        parts = text.splitlines()
        while len(parts) > 1 and len("\n".join(parts)) > budget:
            parts.pop()
        text = "\n".join(parts)
    return text


def needs_compaction(messages: list[dict]) -> bool:
    """True when the chatlog needs compacting: either non-system chars
    exceed COMPACT_TRIGGER_CHARS, or the message COUNT is near the
    _sanitize tail-cap (short-message sessions would otherwise hit the
    500-message cap with NO summary — information must never silently
    leave the context)."""
    non_sys = [m for m in messages if m.get("role") != "system"]
    if sum(len(m.get("content") or "") for m in non_sys) > COMPACT_TRIGGER_CHARS:
        return True
    return len(non_sys) >= COMPACT_TRIGGER_MSGS
